language: python
python: 3.8.2
branches: source
install:
    - pip install mkdocs-material
script:
    - mkdocs build --verbose --clean --strict
deploy:
  provider: pages
  skin_cleanup: true
  github_token: $github_token
  local_dir: site
  target_branch: master
  fqdn: guides.pqtato.pw
  on:
    branch: source
