site_name: Pqtato's Guides
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'green'
    accent: 'light green'
#  icon:
#    logo: material/book
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
repo_name: pqtato-guides/pqtato-guides.github.io
repo_url: https://github.com/pqtato-guides/pqtato-guides.github.io
extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
